package com.model;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class TAdmin implements java.io.Serializable {

	// Fields

	private Integer userId;

	private String userName;

	private String userPw;

	private String userRealname;
	
	private String userAddress;
	
	private String userTel;
	
	private String remark;
	
	private String userType;
	// Constructors

	/** default constructor */
	public TAdmin() {
	}

	public TAdmin(Integer userId, String userName, String userPw,
			String userRealname, String userAddress, String userTel,
			String remark, String userType) {
		super();
		this.userId = userId;
		this.userName = userName;
		this.userPw = userPw;
		this.userRealname = userRealname;
		this.userAddress = userAddress;
		this.userTel = userTel;
		this.remark = remark;
		this.userType = userType;
	}

	public TAdmin(Integer userId, String userName, String userPw,
			String userRealname, String userAddress, String userTel,
			String remark) {
		super();
		this.userId = userId;
		this.userName = userName;
		this.userPw = userPw;
		this.userRealname = userRealname;
		this.userAddress = userAddress;
		this.userTel = userTel;
		this.remark = remark;
	}

	/** full constructor */
	public TAdmin(String userName, String userPw) {
		this.userName = userName;
		this.userPw = userPw;
	}

	// Property accessors


	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return this.userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public Integer getUserId()
	{
		return userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getUserRealname() {
		return userRealname;
	}

	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}

	public String getUserAddress() {
		return userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserTel() {
		return userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

}