package com.model;

/**
 * TChe generated by MyEclipse Persistence Tools
 */

public class TChe implements java.io.Serializable
{

	private Integer id;
	private String chexing;//房租信息
	private String pinpai;//户型
	private String beizhu;//备注

	private String fujian;//图片
	private Integer rizu;//租金
	private String zt;//空闲中----已租出//
	private String del;
	
	private Integer userid;//发布者
	private String quyu;//区域
	private String ttype;//类型
	private String zhxiu;//装修
	private String mianji;//面积
	private String linkman;//联系人
	private String linkphone;//联系电话
	
	private String  bookdate;
	public String getBookdate() {
		return bookdate;
	}
	public void setBookdate(String bookdate) {
		this.bookdate = bookdate;
	}
	public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}
	public String getChexing()
	{
		return chexing;
	}
	public void setChexing(String chexing)
	{
		this.chexing = chexing;
	}
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public String getFujian()
	{
		return fujian;
	}
	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getPinpai()
	{
		return pinpai;
	}
	
	public String getZt()
	{
		return zt;
	}
	public void setZt(String zt)
	{
		this.zt = zt;
	}
	public void setPinpai(String pinpai)
	{
		this.pinpai = pinpai;
	}
	public Integer getRizu()
	{
		return rizu;
	}
	public void setRizu(Integer rizu)
	{
		this.rizu = rizu;
	}
	public Integer getUserid() {
		return userid;
	}
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
	public String getQuyu() {
		return quyu;
	}
	public void setQuyu(String quyu) {
		this.quyu = quyu;
	}
	public String getTtype() {
		return ttype;
	}
	public void setTtype(String ttype) {
		this.ttype = ttype;
	}
	public String getZhxiu() {
		return zhxiu;
	}
	public void setZhxiu(String zhxiu) {
		this.zhxiu = zhxiu;
	}
	public String getMianji() {
		return mianji;
	}
	public void setMianji(String mianji) {
		this.mianji = mianji;
	}
	public String getLinkman() {
		return linkman;
	}
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}
	public String getLinkphone() {
		return linkphone;
	}
	public void setLinkphone(String linkphone) {
		this.linkphone = linkphone;
	}

}