package com.model;

/**
 * TZulin generated by MyEclipse Persistence Tools
 */

public class TZulin implements java.io.Serializable
{

	private Integer id;
	private int cheId;
	private String kehuming;
	private String shenfenzheng;

	private String jiazhaohao;
	private String kaishishijian;
	private Integer yajin;
	private String beizhu;
	
	private String shifouhuan;
	private String jieshushijian;
	private Integer feiyong;
	
	private Integer userId;
	private Integer belonguserId;
	
	private TChe che;

	public String getBeizhu()
	{
		return beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}


	public int getCheId()
	{
		return cheId;
	}

	public void setCheId(int cheId)
	{
		this.cheId = cheId;
	}

	public Integer getFeiyong()
	{
		return feiyong;
	}

	public void setFeiyong(Integer feiyong)
	{
		this.feiyong = feiyong;
	}

	public String getShifouhuan() {
		return shifouhuan;
	}

	public void setShifouhuan(String shifouhuan) {
		this.shifouhuan = shifouhuan;
	}

	public Integer getId()
	{
		return id;
	}


	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getJiazhaohao()
	{
		return jiazhaohao;
	}

	public Integer getYajin()
	{
		return yajin;
	}

	public void setYajin(Integer yajin)
	{
		this.yajin = yajin;
	}

	public void setJiazhaohao(String jiazhaohao)
	{
		this.jiazhaohao = jiazhaohao;
	}

	public String getJieshushijian()
	{
		return jieshushijian;
	}

	public void setJieshushijian(String jieshushijian)
	{
		this.jieshushijian = jieshushijian;
	}

	public String getKaishishijian()
	{
		return kaishishijian;
	}

	public void setKaishishijian(String kaishishijian)
	{
		this.kaishishijian = kaishishijian;
	}

	public String getKehuming()
	{
		return kehuming;
	}

	public TChe getChe()
	{
		return che;
	}

	public void setChe(TChe che)
	{
		this.che = che;
	}

	public void setKehuming(String kehuming)
	{
		this.kehuming = kehuming;
	}

	public String getShenfenzheng()
	{
		return shenfenzheng;
	}

	public void setShenfenzheng(String shenfenzheng)
	{
		this.shenfenzheng = shenfenzheng;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getBelonguserId() {
		return belonguserId;
	}

	public void setBelonguserId(Integer belonguserId) {
		this.belonguserId = belonguserId;
	}
}